'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react';
import { documentsApi } from '@/api/documents';
import { ErrorState, LoadingState, PermissionDeniedState } from '@/components/common-states';
import { GatewayError } from '@/lib/errors';
import type { Document, DocumentVersion } from '@/types/document';
import styles from './documents.module.css';

export function DocumentDetail({ id, taskId }: { id: string; taskId?: string }) { const [document, setDocument] = useState<Document | null>(null); const [versions, setVersions] = useState<DocumentVersion[]>([]); const [status, setStatus] = useState(''); const [preview, setPreview] = useState<{ title: string; security_level: string; document_type: string }>(); const [error, setError] = useState<number>(); const load = () => { setDocument(null); setError(undefined); Promise.all([documentsApi.get(id), documentsApi.versions(id)]).then(([doc, items]) => { setDocument(doc); setVersions(items); }).catch((reason: unknown) => setError(reason instanceof GatewayError ? reason.status : 503)); }; useEffect(load, [id]); const download = async (version: DocumentVersion) => { try { setStatus('Preparing secure download…'); if (!taskId) { setStatus('Download requires an authorized task context.'); return; } const ticket = await documentsApi.ticket(id, version.version, taskId); const blob = await documentsApi.redeem(id, version.version, ticket.id); const url = URL.createObjectURL(blob); const link = window.document.createElement('a'); link.href = url; link.download = document?.title || 'download'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0); setStatus('Download started.'); } catch (reason) { setStatus(reason instanceof GatewayError && reason.status === 403 ? 'This download ticket can no longer be used. Request a new download.' : 'Download could not be completed.'); } }; const getPreview = async () => { try { setPreview(await documentsApi.preview(id)); setStatus('Preview metadata loaded.'); } catch { setStatus('Preview could not be loaded.'); } }; if (error === 403) return <PermissionDeniedState />; if (error) return <ErrorState message="Document details could not be loaded." onRetry={load} />; if (!document) return <LoadingState />; return <section><h1>{document.title}</h1><dl className={styles.metadata}><dt>Type</dt><dd>{document.document_type}</dd><dt>Security level</dt><dd>{document.security_level}</dd><dt>Current version</dt><dd>{document.current_version}</dd><dt>Status</dt><dd>{document.status}</dd></dl>{status && <p role="status">{status}</p>}<button onClick={() => void getPreview()}>Load safe preview metadata</button>{preview && <p>Preview: {preview.title} — {preview.document_type} ({preview.security_level})</p>}{!taskId && <p role="note">Downloads are available only when this document is opened from an authorized task.</p>}<h2>Versions</h2><table><thead><tr><th>Version</th><th>MIME type</th><th>Size</th><th>Action</th></tr></thead><tbody>{versions.map(version => <tr key={version.id}><td>{version.version}</td><td>{version.mime_type}</td><td>{version.file_size.toLocaleString()} bytes</td><td><button onClick={() => void download(version)} disabled={!taskId}>Download</button></td></tr>)}</tbody></table></section>; }
