'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { ChangeEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { documentsApi } from '@/api/documents';
import { EmptyState, ErrorState, LoadingState } from '@/components/common-states';
import type { Document } from '@/types/document';
import styles from './documents.module.css';

export function DocumentList() { const [docs, setDocs] = useState<Document[] | null>(null); const [error, setError] = useState(false); const [file, setFile] = useState<File>(); const [progress, setProgress] = useState(''); const load = () => { setDocs(null); setError(false); documentsApi.list().then(setDocs).catch(() => setError(true)); }; useEffect(load, []); const upload = async (event: ChangeEvent<HTMLFormElement>) => { event.preventDefault(); if (!file) return; const data = new FormData(event.currentTarget); data.set('file', file); setProgress('Uploading: 0%'); try { await documentsApi.upload(data, percent => setProgress(`Uploading: ${percent}%`)); setProgress('Upload completed.'); load(); } catch { setProgress('Upload was not accepted. Check file size, type and metadata.'); } }; if (error) return <ErrorState message="Documents could not be loaded." onRetry={load} />; if (!docs) return <LoadingState />; return <section><div className={styles.head}><div><h1>Documents</h1><p>Secure workspace documents. Ownership is assigned automatically from your signed-in account.</p></div></div><form className={styles.upload} onSubmit={upload}><div className={styles.uploadIntro}><span className={styles.uploadIcon}>?</span><div><h2>Upload a document</h2><p>PDF, Word, images or text up to 25 MB.</p></div></div><label className={styles.dropzone}><input required type="file" onChange={event => setFile(event.target.files?.[0])} /><span className={styles.dropTitle}>{file ? file.name : "Choose a file or drag it here"}</span><span className={styles.dropHint}>{file ? `${Math.ceil(file.size / 1024)} KB selected` : "Your file stays protected in the workspace"}</span></label><div className={styles.fieldGrid}><label>Title<input required name="title" placeholder="e.g. Product brief" /></label><label>Document type<input required name="document_type" placeholder="e.g. Policy" /></label><label>Security level <select name="security_level" defaultValue="INTERNAL"><option>PUBLIC</option><option>INTERNAL</option><option>CONFIDENTIAL</option><option>RESTRICTED</option></select></label><label>Retention policy<input name="retention_policy" placeholder="Optional" /></label></div><input type="hidden" name="declared_state_secret" value="false" /><div className={styles.uploadFooter}><span>{progress || "Owner is set from your account"}</span><button>Upload document</button></div></form>{docs.length === 0 ? <EmptyState title="No documents found">Documents you can view will appear here.</EmptyState> : <div className={styles.tableWrap}><table><thead><tr><th>Document</th><th>Level</th><th>Version</th><th>Updated</th></tr></thead><tbody>{docs.map(document => <tr key={document.id}><td><Link href={`/documents/${document.id}`}>{document.title}</Link></td><td>{document.security_level}</td><td>{document.current_version}</td><td>{new Date(document.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section>; }
