'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { ChangeEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { documentsApi } from '@/api/documents';
import { readSession } from '@/auth/session';
import { EmptyState, ErrorState, LoadingState } from '@/components/common-states';
import type { Document } from '@/types/document';
import styles from './documents.module.css';

export function DocumentList() { const [docs, setDocs] = useState<Document[] | null>(null); const [error, setError] = useState(false); const [file, setFile] = useState<File>(); const [progress, setProgress] = useState(''); const ownerId = readSession()?.userId ?? ''; const load = () => { setDocs(null); setError(false); documentsApi.list().then(setDocs).catch(() => setError(true)); }; useEffect(load, []); const upload = async (event: ChangeEvent<HTMLFormElement>) => { event.preventDefault(); if (!file) return; const data = new FormData(event.currentTarget); data.set('file', file); setProgress('Uploading: 0%'); try { await documentsApi.upload(data, percent => setProgress(`Uploading: ${percent}%`)); setProgress('Upload completed.'); load(); } catch { setProgress('Upload was not accepted. Check file size, type and metadata.'); } }; if (error) return <ErrorState message="Documents could not be loaded." onRetry={load} />; if (!docs) return <LoadingState />; return <section><div className={styles.head}><div><h1>Documents</h1><p>Document metadata and secure download controls. List and version access still await backend permission verification.</p></div></div><form className={styles.upload} onSubmit={upload}><h2>Upload document</h2><label>File <input required type="file" onChange={event => setFile(event.target.files?.[0])} /></label><label>Title <input required name="title" /></label><label>Document type <input required name="document_type" /></label><label>Owner ID <input required name="owner_id" defaultValue={ownerId} /></label><label>Security level <select name="security_level" defaultValue="INTERNAL"><option>PUBLIC</option><option>INTERNAL</option><option>CONFIDENTIAL</option><option>RESTRICTED</option></select></label><label>Retention policy <input name="retention_policy" /></label><input type="hidden" name="declared_state_secret" value="false" /><button>Upload</button>{progress && <p role="status">{progress}</p>}</form>{docs.length === 0 ? <EmptyState title="No documents found">Documents you can view will appear here.</EmptyState> : <div className={styles.tableWrap}><table><thead><tr><th>Document</th><th>Level</th><th>Version</th><th>Updated</th></tr></thead><tbody>{docs.map(document => <tr key={document.id}><td><Link href={`/documents/${document.id}`}>{document.title}</Link></td><td>{document.security_level}</td><td>{document.current_version}</td><td>{new Date(document.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section>; }
