'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useState } from 'react';
import { adminApi } from '@/api/admin';
import { EmptyState, ErrorState, LoadingState, PermissionDeniedState } from '@/components/common-states';
import { readSession } from '@/auth/session';
import type { ManagedUser } from '@/types/admin';
import styles from './admin.module.css';

export function UsersPanel() { const session = readSession(); const [users,setUsers]=useState<ManagedUser[]|null>(null); const [failed,setFailed]=useState(false); const [status,setStatus]=useState(''); const load=()=>{setUsers(null);setFailed(false);adminApi.users().then(setUsers).catch(()=>setFailed(true));}; useEffect(load,[]);
  if(session?.role!=='ADMIN') return <PermissionDeniedState/>; if(failed)return <ErrorState message="Users could not be loaded." onRetry={load}/>;if(!users)return <LoadingState/>;
  const change=async(action:()=>Promise<unknown>,message:string)=>{setStatus('Sending request…');try{await action();setStatus(message);load();}catch{setStatus('The server did not accept that change.');}};
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await change(()=>adminApi.createUser({id:String(f.get('id')),email:String(f.get('email')),role:String(f.get('role')) as ManagedUser['role']}),'User created from the server response.');};
  return <section><h1>Users & capabilities</h1><p className={styles.notice}>ADMIN-only presentation guard. The current backend controller does not enforce the ADMIN role; server authorization must be fixed and runtime-verified.</p><div className={styles.grid}><section className={styles.panel}><h2>Create user</h2><form className={styles.form} onSubmit={create}><label>User ID (UUID)<input name="id" required/></label><label>Email<input name="email" type="email" required/></label><label>Role<select name="role"><option>EMPLOYEE</option><option>ADMIN</option></select></label><button>Create user</button></form></section><section className={styles.panel}><h2>Capability change</h2><p className={styles.muted}>Capabilities are only available to EMPLOYEE accounts; server rules are reconciled after each request.</p></section></div>{status&&<p role="status">{status}</p>}{users.length===0?<EmptyState title="No users returned">No user records are available.</EmptyState>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Email</th><th>Role</th><th>Account</th><th>Capabilities</th><th>Actions</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td>{user.email}</td><td>{user.role}</td><td>{user.locked_at?'Locked':'Active'}</td><td><div className={styles.chips}>{user.capabilities.map(cap=><span className={styles.chip} key={cap}>{cap} <button aria-label={`Revoke ${cap}`} onClick={()=>change(()=>adminApi.revokeCapability(user.id,cap),'Capability revoked from the server response.')}>×</button></span>)}</div><form className={styles.actions} onSubmit={e=>{e.preventDefault();const cap=String(new FormData(e.currentTarget).get('capability'));change(()=>adminApi.grantCapability(user.id,cap),'Capability granted from the server response.');}}><input name="capability" aria-label={`Capability for ${user.email}`} required/><button>Add</button></form></td><td><button onClick={()=>change(()=>user.locked_at?adminApi.unlock(user.id):adminApi.lock(user.id),user.locked_at?'User unlocked from the server response.':'User locked from the server response.')}>{user.locked_at?'Unlock':'Lock'}</button></td></tr>)}</tbody></table></div>}</section>; }
