'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { ChangeEvent, useEffect, useState } from 'react';
import { notificationsApi } from '@/api/notifications';
import { readSession } from '@/auth/session';
import { EmptyState, ErrorState, LoadingState } from '@/components/common-states';
import type { Notification, NotificationPreference } from '@/types/notification';
import styles from './notifications.module.css';

export function NotificationList() {
  const session = readSession(); const userId = session?.userId; const [items, setItems] = useState<Notification[] | null>(null); const [preferences, setPreferences] = useState<NotificationPreference | null>(null); const [unreadOnly, setUnreadOnly] = useState(false); const [error, setError] = useState(false); const [message, setMessage] = useState('');
  const load = () => { if (!userId) return; setItems(null); setError(false); Promise.all([notificationsApi.list(userId, unreadOnly), notificationsApi.preferences(userId)]).then(([listed, prefs]) => { setItems(listed); setPreferences(prefs); }).catch(() => setError(true)); };
  useEffect(load, [userId, unreadOnly]);
  if (!userId) return <ErrorState message="A session identity hint is unavailable. Please sign in again." />;
  const markRead = async (id: string) => { try { const updated = await notificationsApi.markRead(id); setItems(current => current?.map(item => item.id === id ? updated : item) ?? null); setMessage('Notification marked read by the server.'); } catch { setMessage('The server did not accept the read update.'); } };
  const markAll = async () => { try { const result = await notificationsApi.markAllRead(userId); setItems(current => current?.map(item => item.read_at ? item : { ...item, read_at: new Date().toISOString() }) ?? null); setMessage(`${result.count} notifications marked read by the server.`); } catch { setMessage('The server did not accept the read-all update.'); } };
  const changePreference = async (event: ChangeEvent<HTMLInputElement>) => { if (!preferences) return; const next = { ...preferences, [event.target.name]: event.target.checked }; setPreferences(next); try { const updated = await notificationsApi.updatePreferences(userId, { email_enabled: next.email_enabled, in_app_enabled: next.in_app_enabled }); setPreferences(updated); setMessage('Preferences updated by the server.'); } catch { setPreferences(preferences); setMessage('The server did not accept the preference update.'); } };
  if (error) return <ErrorState message="Notifications could not be loaded." onRetry={load} />; if (!items || !preferences) return <LoadingState />;
  return <section><div className={styles.head}><div><h1>Notifications</h1><p>In-app notifications only. This screen does not claim realtime, push, or email delivery.</p></div></div><p className={styles.notice}>The backend currently accepts recipient and preference user IDs from the request without an ownership guard. Your JWT subject is used only as a UX hint; server authorization still requires a backend fix.</p><div className={styles.toolbar}><label><input type="checkbox" checked={unreadOnly} onChange={event => setUnreadOnly(event.target.checked)} /> Unread only</label><button onClick={markAll} disabled={!items.some(item => item.read_at === null)}>Mark all read</button>{message && <p role="status">{message}</p>}</div>{items.length === 0 ? <EmptyState title="No notifications">Notifications addressed to this session hint will appear here.</EmptyState> : <ul className={styles.list}>{items.map(item => <li className={`${styles.item} ${item.read_at === null ? styles.unread : ''}`} key={item.id}><h2>{item.title}</h2><p>{item.body}</p><p className={styles.meta}>{item.type} · {new Date(item.created_at).toLocaleString()} · {item.read_at ? 'Read' : 'Unread'}</p>{item.read_at === null && <button onClick={() => markRead(item.id)}>Mark read</button>}</li>)}</ul>}<section className={styles.prefs} aria-labelledby="preferences-title"><h2 id="preferences-title">Delivery preferences</h2><label><input type="checkbox" name="in_app_enabled" checked={preferences.in_app_enabled} onChange={changePreference} /> In-app notifications</label><label><input type="checkbox" name="email_enabled" checked={preferences.email_enabled} onChange={changePreference} /> Email notifications</label></section></section>;
}
