'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useState } from 'react';
import { tasksApi } from '@/api/tasks';
import { ErrorState, LoadingState, PermissionDeniedState } from '@/components/common-states';
import { GatewayError } from '@/lib/errors';
import type { Activity, AncestorTaskSummary, Participant, Task, TaskComment, TaskStatus } from '@/types/task';
import styles from './tasks.module.css';

const isSummary = (value: Task | AncestorTaskSummary): value is AncestorTaskSummary => !('id' in value);
const message = (error: unknown, fallback: string) => error instanceof GatewayError && error.status === 409 ? 'This task changed. Refresh and try again.' : fallback;

export function TaskDetail({ id }: { id: string }) {
  const [task, setTask] = useState<Task | AncestorTaskSummary | null>(null); const [comments, setComments] = useState<TaskComment[]>([]); const [activity, setActivity] = useState<Activity[]>([]); const [participants, setParticipants] = useState<Participant[]>([]); const [error, setError] = useState<number>();
  const load = () => { setError(undefined); setTask(null); tasksApi.get(id).then(async result => { setTask(result); if (!isSummary(result)) { const [participantItems, activityItems, commentItems] = await Promise.all([tasksApi.participants(id), tasksApi.activity(id), tasksApi.comments(id)]); setParticipants(participantItems); setActivity(activityItems); setComments(commentItems); } }).catch((reason: unknown) => setError(reason instanceof GatewayError ? reason.status : 503)); };
  useEffect(load, [id]);
  if (error === 403) return <PermissionDeniedState />;
  if (error) return <ErrorState message="Task details could not be loaded." onRetry={load} />;
  if (!task) return <LoadingState />;
  if (isSummary(task)) return <section className={styles.detail}><h1>{task.title}</h1><p className={styles.summary}>Ancestor oversight: summary only. Comments, activity, participants and documents are unavailable.</p><dl><dt>Status</dt><dd>{task.status}</dd><dt>Assignee</dt><dd>{task.assignee ?? 'Unassigned'}</dd><dt>Deadline</dt><dd>{task.deadline ?? '—'}</dd><dt>Overdue</dt><dd>{task.is_overdue ? 'Yes' : 'No'}</dd><dt>Result</dt><dd>{task.completion_result ?? '—'}</dd></dl></section>;
  return <DirectTask task={task} comments={comments} activity={activity} participants={participants} reload={load} />;
}

function DirectTask({ task, comments, activity, participants, reload }: { task: Task; comments: TaskComment[]; activity: Activity[]; participants: Participant[]; reload: () => void }) {
  const [notice, setNotice] = useState(''); const act = async (work: () => Promise<unknown>, success: string, fallback: string) => { try { await work(); setNotice(success); reload(); } catch (error) { setNotice(message(error, fallback)); } };
  const comment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const content = String(new FormData(event.currentTarget).get('content')); void act(() => tasksApi.comment(task.id, content), 'Comment added.', 'Comment could not be added.'); event.currentTarget.reset(); };
  const assign = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const assigneeId = String(new FormData(event.currentTarget).get('assignee_id')); void act(() => tasksApi.assign(task.id, assigneeId), 'Task assigned.', 'Task assignment was not accepted.'); };
  const participant = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(() => tasksApi.addParticipant(task.id, String(data.get('user_id')), String(data.get('role')) || undefined), 'Participant added.', 'Participant could not be added.'); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const content = String(new FormData(event.currentTarget).get('content')); void act(() => tasksApi.submit(task.id, content), 'Result submitted for review.', 'Result could not be submitted.'); };
  const review = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void act(() => tasksApi.review(String(data.get('submission_id')), String(data.get('decision')) as 'APPROVED' | 'NEED_REVISION' | 'REJECTED', String(data.get('comment')) || undefined), 'Review recorded.', 'Review could not be recorded.'); };
  const transitions: TaskStatus[] = ['IN_PROGRESS', 'CANCELLED'];
  return <section className={styles.detail}><div className={styles.toolbar}><div><h1>{task.title}</h1><p>{task.description}</p></div><span className={styles.status}>{task.blocked ? 'BLOCKED' : task.status}</span></div>{notice && <p role="status">{notice}</p>}<dl><dt>Assignee</dt><dd>{task.assignee_id ?? 'Unassigned'}</dd><dt>Deadline</dt><dd>{task.deadline ?? '—'}</dd><dt>Condition</dt><dd>{task.is_overdue ? 'Overdue' : task.blocked ? 'Blocked' : 'On track'}</dd></dl><div className={styles.actions}>{transitions.includes('IN_PROGRESS') && (task.status === 'ASSIGNED' || task.status === 'NEED_REVISION') && <button onClick={() => void act(() => tasksApi.status(task.id, 'IN_PROGRESS'), 'Task updated.', 'Task update was not accepted.')}>Start work</button>}{!['APPROVED', 'REJECTED', 'CANCELLED'].includes(task.status) && <button className={styles.secondary} onClick={() => { if (confirm('Cancel this task?')) void act(() => tasksApi.status(task.id, 'CANCELLED'), 'Task cancelled.', 'Task update was not accepted.'); }}>Cancel task</button>}<button className={styles.secondary} onClick={() => { const reason = prompt('Why is this task blocked?'); if (reason) void act(() => tasksApi.block(task.id, reason), 'Task blocked.', 'Task could not be blocked.'); }}>{task.blocked ? 'Update block' : 'Block task'}</button>{task.blocked && <button className={styles.secondary} onClick={() => void act(() => tasksApi.unblock(task.id), 'Task unblocked.', 'Task could not be unblocked.')}>Unblock task</button>}</div><form className={styles.inlineForm} onSubmit={assign}><h2>Assign task</h2><label>Employee ID<input name="assignee_id" required /></label><button>Assign</button></form><form className={styles.inlineForm} onSubmit={participant}><h2>Add participant</h2><label>Employee ID<input name="user_id" required /></label><label>Role (optional)<input name="role" /></label><button>Add participant</button></form><h2>Participants</h2><ul>{participants.map(item => <li key={item.id}>{item.user_id} — {item.role}</li>)}</ul><form className={styles.inlineForm} onSubmit={submit}><h2>Submit result</h2><label>Result<textarea name="content" required /></label><button>Submit for review</button></form><form className={styles.inlineForm} onSubmit={review}><h2>Review submission</h2><label>Submission ID<input name="submission_id" required /></label><label>Decision<select name="decision"><option>APPROVED</option><option>NEED_REVISION</option><option>REJECTED</option></select></label><label>Comment (optional)<input name="comment" /></label><button>Record review</button></form><h2>Activity</h2><ol>{activity.map(item => <li key={item.id}>{item.summary} <small>{new Date(item.created_at).toLocaleString()}</small></li>)}</ol><h2>Comments</h2><ul>{comments.map(item => <li key={item.id}>{item.content}</li>)}</ul><form onSubmit={comment}><label htmlFor="comment">Add a comment</label><textarea id="comment" name="content" required /><button>Post comment</button></form></section>;
}
